
package us.kbase.kbasecmonkey;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;
import org.codehaus.jackson.annotate.JsonAnyGetter;
import org.codehaus.jackson.annotate.JsonAnySetter;
import org.codehaus.jackson.annotate.JsonProperty;
import org.codehaus.jackson.annotate.JsonPropertyOrder;
import org.codehaus.jackson.map.annotate.JsonSerialize;


/**
 * <p>Original spec-file type: CmonkeyCluster</p>
 * <pre>
 * Represents bicluster generated by cMonkey
 * string CmonkeyClusterId - identifier of bicluster
 * int numGenes - number of genes
 * int numConditions - number of conditions
 * float clusterResidual - residual
 * list<string> clusterExpressionDataSetIds - list of experimental conditions 
 * list<string> clusterGeneIds - list of genes from bicluster
 * list<MotifCmonkey> clusterMotifs - list of motifs identified for the bicluster, converted to MEME format
 * </pre>
 * 
 */
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "CmonkeyClusterId",
    "numGenes",
    "numConditions",
    "clusterResidual",
    "clusterExpressionDataSetIds",
    "clusterGeneIds",
    "clusterMotifs"
})
public class CmonkeyCluster {

    @JsonProperty("CmonkeyClusterId")
    private String CmonkeyClusterId;
    @JsonProperty("numGenes")
    private Integer numGenes;
    @JsonProperty("numConditions")
    private Integer numConditions;
    @JsonProperty("clusterResidual")
    private Double clusterResidual;
    @JsonProperty("clusterExpressionDataSetIds")
    private List<String> clusterExpressionDataSetIds = new ArrayList<String>();
    @JsonProperty("clusterGeneIds")
    private List<String> clusterGeneIds = new ArrayList<String>();
    @JsonProperty("clusterMotifs")
    private List<MotifCmonkey> clusterMotifs = new ArrayList<MotifCmonkey>();
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("CmonkeyClusterId")
    public String getCmonkeyClusterId() {
        return CmonkeyClusterId;
    }

    @JsonProperty("CmonkeyClusterId")
    public void setCmonkeyClusterId(String CmonkeyClusterId) {
        this.CmonkeyClusterId = CmonkeyClusterId;
    }

    public CmonkeyCluster withCmonkeyClusterId(String CmonkeyClusterId) {
        this.CmonkeyClusterId = CmonkeyClusterId;
        return this;
    }

    @JsonProperty("numGenes")
    public Integer getNumGenes() {
        return numGenes;
    }

    @JsonProperty("numGenes")
    public void setNumGenes(Integer numGenes) {
        this.numGenes = numGenes;
    }

    public CmonkeyCluster withNumGenes(Integer numGenes) {
        this.numGenes = numGenes;
        return this;
    }

    @JsonProperty("numConditions")
    public Integer getNumConditions() {
        return numConditions;
    }

    @JsonProperty("numConditions")
    public void setNumConditions(Integer numConditions) {
        this.numConditions = numConditions;
    }

    public CmonkeyCluster withNumConditions(Integer numConditions) {
        this.numConditions = numConditions;
        return this;
    }

    @JsonProperty("clusterResidual")
    public Double getClusterResidual() {
        return clusterResidual;
    }

    @JsonProperty("clusterResidual")
    public void setClusterResidual(Double clusterResidual) {
        this.clusterResidual = clusterResidual;
    }

    public CmonkeyCluster withClusterResidual(Double clusterResidual) {
        this.clusterResidual = clusterResidual;
        return this;
    }

    @JsonProperty("clusterExpressionDataSetIds")
    public List<String> getClusterExpressionDataSetIds() {
        return clusterExpressionDataSetIds;
    }

    @JsonProperty("clusterExpressionDataSetIds")
    public void setClusterExpressionDataSetIds(List<String> clusterExpressionDataSetIds) {
        this.clusterExpressionDataSetIds = clusterExpressionDataSetIds;
    }

    public CmonkeyCluster withClusterExpressionDataSetIds(List<String> clusterExpressionDataSetIds) {
        this.clusterExpressionDataSetIds = clusterExpressionDataSetIds;
        return this;
    }

    @JsonProperty("clusterGeneIds")
    public List<String> getClusterGeneIds() {
        return clusterGeneIds;
    }

    @JsonProperty("clusterGeneIds")
    public void setClusterGeneIds(List<String> clusterGeneIds) {
        this.clusterGeneIds = clusterGeneIds;
    }

    public CmonkeyCluster withClusterGeneIds(List<String> clusterGeneIds) {
        this.clusterGeneIds = clusterGeneIds;
        return this;
    }

    @JsonProperty("clusterMotifs")
    public List<MotifCmonkey> getClusterMotifs() {
        return clusterMotifs;
    }

    @JsonProperty("clusterMotifs")
    public void setClusterMotifs(List<MotifCmonkey> clusterMotifs) {
        this.clusterMotifs = clusterMotifs;
    }

    public CmonkeyCluster withClusterMotifs(List<MotifCmonkey> clusterMotifs) {
        this.clusterMotifs = clusterMotifs;
        return this;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
