
package us.kbase.kbasecmonkey;

import java.util.HashMap;
import java.util.Map;
import javax.annotation.Generated;
import org.codehaus.jackson.annotate.JsonAnyGetter;
import org.codehaus.jackson.annotate.JsonAnySetter;
import org.codehaus.jackson.annotate.JsonProperty;
import org.codehaus.jackson.annotate.JsonPropertyOrder;
import org.codehaus.jackson.map.annotate.JsonSerialize;


/**
 * <p>Original spec-file type: CmonkeyRun</p>
 * <pre>
 * Represents data from a single run of cMonkey
 * string cmonkeyRunId - identifier or cMonkey run
 * string cmonkeyRunStartTime - start time of cMonkey run
 * string cmonkeyRunFinishTime - end time of cMonkey run
 * int cmonkeyRunNumIterations - number of iterations
 * int cmonkeyRunLastIteration - last iteration
 * string cmonkeyRunOrganism - organism
 * int cmonkeyRunNumRows - number of rows
 * int cmonkeyRunNumColumns - number of columns
 * int cmonkeyRunNumClusters - number of clusters
 * CmonkeyNetwork cmonkeyNetwork;
 * </pre>
 * 
 */
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "cmonkeyRunId",
    "cmonkeyRunStartTime",
    "cmonkeyRunFinishTime",
    "cmonkeyRunNumIterations",
    "cmonkeyRunLastIteration",
    "cmonkeyRunOrganism",
    "cmonkeyRunNumRows",
    "cmonkeyRunNumColumns",
    "cmonkeyRunNumClusters",
    "cmonkeyNetwork"
})
public class CmonkeyRun {

    @JsonProperty("cmonkeyRunId")
    private String cmonkeyRunId;
    @JsonProperty("cmonkeyRunStartTime")
    private String cmonkeyRunStartTime;
    @JsonProperty("cmonkeyRunFinishTime")
    private String cmonkeyRunFinishTime;
    @JsonProperty("cmonkeyRunNumIterations")
    private Integer cmonkeyRunNumIterations;
    @JsonProperty("cmonkeyRunLastIteration")
    private Integer cmonkeyRunLastIteration;
    @JsonProperty("cmonkeyRunOrganism")
    private String cmonkeyRunOrganism;
    @JsonProperty("cmonkeyRunNumRows")
    private Integer cmonkeyRunNumRows;
    @JsonProperty("cmonkeyRunNumColumns")
    private Integer cmonkeyRunNumColumns;
    @JsonProperty("cmonkeyRunNumClusters")
    private Integer cmonkeyRunNumClusters;
    /**
     * <p>Original spec-file type: CmonkeyNetwork</p>
     * <pre>
     * Represents network generated by a single run of cMonkey
     * string CmonkeyNetworkId - identifier of cMonkey-generated network
     * int Iteration - number of the last iteration
     * list<CmonkeyCluster> cmonkeyClusters - list of biclusters
     * </pre>
     * 
     */
    @JsonProperty("cmonkeyNetwork")
    private CmonkeyNetwork cmonkeyNetwork;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("cmonkeyRunId")
    public String getCmonkeyRunId() {
        return cmonkeyRunId;
    }

    @JsonProperty("cmonkeyRunId")
    public void setCmonkeyRunId(String cmonkeyRunId) {
        this.cmonkeyRunId = cmonkeyRunId;
    }

    public CmonkeyRun withCmonkeyRunId(String cmonkeyRunId) {
        this.cmonkeyRunId = cmonkeyRunId;
        return this;
    }

    @JsonProperty("cmonkeyRunStartTime")
    public String getCmonkeyRunStartTime() {
        return cmonkeyRunStartTime;
    }

    @JsonProperty("cmonkeyRunStartTime")
    public void setCmonkeyRunStartTime(String cmonkeyRunStartTime) {
        this.cmonkeyRunStartTime = cmonkeyRunStartTime;
    }

    public CmonkeyRun withCmonkeyRunStartTime(String cmonkeyRunStartTime) {
        this.cmonkeyRunStartTime = cmonkeyRunStartTime;
        return this;
    }

    @JsonProperty("cmonkeyRunFinishTime")
    public String getCmonkeyRunFinishTime() {
        return cmonkeyRunFinishTime;
    }

    @JsonProperty("cmonkeyRunFinishTime")
    public void setCmonkeyRunFinishTime(String cmonkeyRunFinishTime) {
        this.cmonkeyRunFinishTime = cmonkeyRunFinishTime;
    }

    public CmonkeyRun withCmonkeyRunFinishTime(String cmonkeyRunFinishTime) {
        this.cmonkeyRunFinishTime = cmonkeyRunFinishTime;
        return this;
    }

    @JsonProperty("cmonkeyRunNumIterations")
    public Integer getCmonkeyRunNumIterations() {
        return cmonkeyRunNumIterations;
    }

    @JsonProperty("cmonkeyRunNumIterations")
    public void setCmonkeyRunNumIterations(Integer cmonkeyRunNumIterations) {
        this.cmonkeyRunNumIterations = cmonkeyRunNumIterations;
    }

    public CmonkeyRun withCmonkeyRunNumIterations(Integer cmonkeyRunNumIterations) {
        this.cmonkeyRunNumIterations = cmonkeyRunNumIterations;
        return this;
    }

    @JsonProperty("cmonkeyRunLastIteration")
    public Integer getCmonkeyRunLastIteration() {
        return cmonkeyRunLastIteration;
    }

    @JsonProperty("cmonkeyRunLastIteration")
    public void setCmonkeyRunLastIteration(Integer cmonkeyRunLastIteration) {
        this.cmonkeyRunLastIteration = cmonkeyRunLastIteration;
    }

    public CmonkeyRun withCmonkeyRunLastIteration(Integer cmonkeyRunLastIteration) {
        this.cmonkeyRunLastIteration = cmonkeyRunLastIteration;
        return this;
    }

    @JsonProperty("cmonkeyRunOrganism")
    public String getCmonkeyRunOrganism() {
        return cmonkeyRunOrganism;
    }

    @JsonProperty("cmonkeyRunOrganism")
    public void setCmonkeyRunOrganism(String cmonkeyRunOrganism) {
        this.cmonkeyRunOrganism = cmonkeyRunOrganism;
    }

    public CmonkeyRun withCmonkeyRunOrganism(String cmonkeyRunOrganism) {
        this.cmonkeyRunOrganism = cmonkeyRunOrganism;
        return this;
    }

    @JsonProperty("cmonkeyRunNumRows")
    public Integer getCmonkeyRunNumRows() {
        return cmonkeyRunNumRows;
    }

    @JsonProperty("cmonkeyRunNumRows")
    public void setCmonkeyRunNumRows(Integer cmonkeyRunNumRows) {
        this.cmonkeyRunNumRows = cmonkeyRunNumRows;
    }

    public CmonkeyRun withCmonkeyRunNumRows(Integer cmonkeyRunNumRows) {
        this.cmonkeyRunNumRows = cmonkeyRunNumRows;
        return this;
    }

    @JsonProperty("cmonkeyRunNumColumns")
    public Integer getCmonkeyRunNumColumns() {
        return cmonkeyRunNumColumns;
    }

    @JsonProperty("cmonkeyRunNumColumns")
    public void setCmonkeyRunNumColumns(Integer cmonkeyRunNumColumns) {
        this.cmonkeyRunNumColumns = cmonkeyRunNumColumns;
    }

    public CmonkeyRun withCmonkeyRunNumColumns(Integer cmonkeyRunNumColumns) {
        this.cmonkeyRunNumColumns = cmonkeyRunNumColumns;
        return this;
    }

    @JsonProperty("cmonkeyRunNumClusters")
    public Integer getCmonkeyRunNumClusters() {
        return cmonkeyRunNumClusters;
    }

    @JsonProperty("cmonkeyRunNumClusters")
    public void setCmonkeyRunNumClusters(Integer cmonkeyRunNumClusters) {
        this.cmonkeyRunNumClusters = cmonkeyRunNumClusters;
    }

    public CmonkeyRun withCmonkeyRunNumClusters(Integer cmonkeyRunNumClusters) {
        this.cmonkeyRunNumClusters = cmonkeyRunNumClusters;
        return this;
    }

    /**
     * <p>Original spec-file type: CmonkeyNetwork</p>
     * <pre>
     * Represents network generated by a single run of cMonkey
     * string CmonkeyNetworkId - identifier of cMonkey-generated network
     * int Iteration - number of the last iteration
     * list<CmonkeyCluster> cmonkeyClusters - list of biclusters
     * </pre>
     * 
     */
    @JsonProperty("cmonkeyNetwork")
    public CmonkeyNetwork getCmonkeyNetwork() {
        return cmonkeyNetwork;
    }

    /**
     * <p>Original spec-file type: CmonkeyNetwork</p>
     * <pre>
     * Represents network generated by a single run of cMonkey
     * string CmonkeyNetworkId - identifier of cMonkey-generated network
     * int Iteration - number of the last iteration
     * list<CmonkeyCluster> cmonkeyClusters - list of biclusters
     * </pre>
     * 
     */
    @JsonProperty("cmonkeyNetwork")
    public void setCmonkeyNetwork(CmonkeyNetwork cmonkeyNetwork) {
        this.cmonkeyNetwork = cmonkeyNetwork;
    }

    public CmonkeyRun withCmonkeyNetwork(CmonkeyNetwork cmonkeyNetwork) {
        this.cmonkeyNetwork = cmonkeyNetwork;
        return this;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
