
package us.kbase.kbasecmonkey;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;
import org.codehaus.jackson.annotate.JsonAnyGetter;
import org.codehaus.jackson.annotate.JsonAnySetter;
import org.codehaus.jackson.annotate.JsonProperty;
import org.codehaus.jackson.annotate.JsonPropertyOrder;
import org.codehaus.jackson.map.annotate.JsonSerialize;


/**
 * <p>Original spec-file type: CmonkeyNetwork</p>
 * <pre>
 * Represents network generated by a single run of cMonkey
 * string CmonkeyNetworkId - identifier of cMonkey-generated network
 * int Iteration - number of the last iteration
 * list<CmonkeyCluster> cmonkeyClusters - list of biclusters
 * </pre>
 * 
 */
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "CmonkeyNetworkId",
    "Iteration",
    "cmonkeyClusters"
})
public class CmonkeyNetwork {

    @JsonProperty("CmonkeyNetworkId")
    private String CmonkeyNetworkId;
    @JsonProperty("Iteration")
    private Integer Iteration;
    @JsonProperty("cmonkeyClusters")
    private List<CmonkeyCluster> cmonkeyClusters = new ArrayList<CmonkeyCluster>();
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("CmonkeyNetworkId")
    public String getCmonkeyNetworkId() {
        return CmonkeyNetworkId;
    }

    @JsonProperty("CmonkeyNetworkId")
    public void setCmonkeyNetworkId(String CmonkeyNetworkId) {
        this.CmonkeyNetworkId = CmonkeyNetworkId;
    }

    public CmonkeyNetwork withCmonkeyNetworkId(String CmonkeyNetworkId) {
        this.CmonkeyNetworkId = CmonkeyNetworkId;
        return this;
    }

    @JsonProperty("Iteration")
    public Integer getIteration() {
        return Iteration;
    }

    @JsonProperty("Iteration")
    public void setIteration(Integer Iteration) {
        this.Iteration = Iteration;
    }

    public CmonkeyNetwork withIteration(Integer Iteration) {
        this.Iteration = Iteration;
        return this;
    }

    @JsonProperty("cmonkeyClusters")
    public List<CmonkeyCluster> getCmonkeyClusters() {
        return cmonkeyClusters;
    }

    @JsonProperty("cmonkeyClusters")
    public void setCmonkeyClusters(List<CmonkeyCluster> cmonkeyClusters) {
        this.cmonkeyClusters = cmonkeyClusters;
    }

    public CmonkeyNetwork withCmonkeyClusters(List<CmonkeyCluster> cmonkeyClusters) {
        this.cmonkeyClusters = cmonkeyClusters;
        return this;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
