
package us.kbase.kbasecmonkey;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;
import org.codehaus.jackson.annotate.JsonAnyGetter;
import org.codehaus.jackson.annotate.JsonAnySetter;
import org.codehaus.jackson.annotate.JsonProperty;
import org.codehaus.jackson.annotate.JsonPropertyOrder;
import org.codehaus.jackson.map.annotate.JsonSerialize;


/**
 * <p>Original spec-file type: MotifCmonkey</p>
 * <pre>
 * Represents motif generated by cMonkey with a list of hits in upstream sequences
 * string CmonkeyMotifId - identifier of MotifCmonkey
 * string seqType - type of sequence
 * int motifNumber - number of motif
 * float evalue - motif e-value
 * list<PssmRow> pssm - PSSM 
 * list<HitMast> hits - hits (motif annotations)
 * </pre>
 * 
 */
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "CmonkeyMotifId",
    "seqType",
    "motifNumber",
    "evalue",
    "pssm",
    "hits"
})
public class MotifCmonkey {

    @JsonProperty("CmonkeyMotifId")
    private String CmonkeyMotifId;
    @JsonProperty("seqType")
    private String seqType;
    @JsonProperty("motifNumber")
    private Integer motifNumber;
    @JsonProperty("evalue")
    private Double evalue;
    @JsonProperty("pssm")
    private List<PssmRow> pssm = new ArrayList<PssmRow>();
    @JsonProperty("hits")
    private List<HitMast> hits = new ArrayList<HitMast>();
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("CmonkeyMotifId")
    public String getCmonkeyMotifId() {
        return CmonkeyMotifId;
    }

    @JsonProperty("CmonkeyMotifId")
    public void setCmonkeyMotifId(String CmonkeyMotifId) {
        this.CmonkeyMotifId = CmonkeyMotifId;
    }

    public MotifCmonkey withCmonkeyMotifId(String CmonkeyMotifId) {
        this.CmonkeyMotifId = CmonkeyMotifId;
        return this;
    }

    @JsonProperty("seqType")
    public String getSeqType() {
        return seqType;
    }

    @JsonProperty("seqType")
    public void setSeqType(String seqType) {
        this.seqType = seqType;
    }

    public MotifCmonkey withSeqType(String seqType) {
        this.seqType = seqType;
        return this;
    }

    @JsonProperty("motifNumber")
    public Integer getMotifNumber() {
        return motifNumber;
    }

    @JsonProperty("motifNumber")
    public void setMotifNumber(Integer motifNumber) {
        this.motifNumber = motifNumber;
    }

    public MotifCmonkey withMotifNumber(Integer motifNumber) {
        this.motifNumber = motifNumber;
        return this;
    }

    @JsonProperty("evalue")
    public Double getEvalue() {
        return evalue;
    }

    @JsonProperty("evalue")
    public void setEvalue(Double evalue) {
        this.evalue = evalue;
    }

    public MotifCmonkey withEvalue(Double evalue) {
        this.evalue = evalue;
        return this;
    }

    @JsonProperty("pssm")
    public List<PssmRow> getPssm() {
        return pssm;
    }

    @JsonProperty("pssm")
    public void setPssm(List<PssmRow> pssm) {
        this.pssm = pssm;
    }

    public MotifCmonkey withPssm(List<PssmRow> pssm) {
        this.pssm = pssm;
        return this;
    }

    @JsonProperty("hits")
    public List<HitMast> getHits() {
        return hits;
    }

    @JsonProperty("hits")
    public void setHits(List<HitMast> hits) {
        this.hits = hits;
    }

    public MotifCmonkey withHits(List<HitMast> hits) {
        this.hits = hits;
        return this;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
