package us.kbase.cmonkey;

import us.kbase.auth.AuthToken;
import us.kbase.common.service.JsonServerMethod;
import us.kbase.common.service.JsonServerServlet;

//BEGIN_HEADER
//END_HEADER

/**
 * <p>Original spec-file module name: Cmonkey</p>
 * <pre>
 * Module KBaseCmonkey version 1.0
 * This module provides a set of methods for work with cMonkey biclustering tool.
 * Data types summary
 * Input data types: 
 * ExpressionDataSeries represents a list of expression data samples that serve as an input of cMonkey.
 * ExpressionDataSample data type represents a sample of expression data for a single condition.
 * ExpressionDataPoint data type represents a relative expression value for a single gene.
 * Output data types:
 * CmonkeyRun data type represents data generated by a single run of cMonkey (run_infos table of cMonkey results)
 * CmonkeyNetwork data type represents bicluster network
 * CmonkeyCluter data type represents a single bicluster from cMonkey network, with links to genes, experimental conditions and motifs
 * CmonkeyMotif data type represents a single motif identifed for a bicluster
 * Methods summary
 * build_cmonkey_network - Starts cMonkey server run for a series of expression data and returns job ID of the run 
 * build_cmonkey_network_from_ws - Starts cMonkey server run for a series of expression data stored in workspace and returns job ID of the run
 * build_cmonkey_network_job_from_ws - Starts cMonkey server run for a series of expression data stored in workspace and returns job ID of the run
 * </pre>
 */
public class CmonkeyServer extends JsonServerServlet {
    private static final long serialVersionUID = 1L;

    //BEGIN_CLASS_HEADER
    //END_CLASS_HEADER

    public CmonkeyServer() throws Exception {
        super("Cmonkey");
        //BEGIN_CONSTRUCTOR
        CmonkeyServerImpl.cleanUpOnStart();
        //END_CONSTRUCTOR
    }

    /**
     * <p>Original spec-file function name: build_cmonkey_network</p>
     * <pre>
     * Starts cMonkey server run for a series of expression data and returns run result 
     * ExpressionDataSeries series - series of expression data samples for cMonkey run
     * CmonkeyRunParameters params - parameters of cMonkey run
     * string job_id - identifier of cMonkey job
     * </pre>
     * @param   series   instance of type {@link us.kbase.cmonkey.ExpressionDataSeries ExpressionDataSeries}
     * @param   params   instance of type {@link us.kbase.cmonkey.CmonkeyRunParameters CmonkeyRunParameters}
     * @return   parameter "cmonkey_run_result" of type {@link us.kbase.cmonkey.CmonkeyRunResult CmonkeyRunResult}
     */
    @JsonServerMethod(rpc = "Cmonkey.build_cmonkey_network")
    public CmonkeyRunResult buildCmonkeyNetwork(ExpressionDataSeries series, CmonkeyRunParameters params) throws Exception {
        CmonkeyRunResult returnVal = null;
        //BEGIN build_cmonkey_network
        returnVal = CmonkeyServerCaller.buildCmonkeyNetwork(series, params);
        //END build_cmonkey_network
        return returnVal;
    }

    /**
     * <p>Original spec-file function name: build_cmonkey_network_from_ws</p>
     * <pre>
     * Starts cMonkey server run for a series of expression data stored in workspace and returns ID of the run result object
     * string ws_id - workspace id
     * string series_id - kbase id of expression data series for cMonkey run
     * CmonkeyRunParameters params - parameters of cMonkey run
     * string job_id - identifier of cMonkey job
     * </pre>
     * @param   wsId   instance of String
     * @param   collectionId   instance of String
     * @param   params   instance of type {@link us.kbase.cmonkey.CmonkeyRunParameters CmonkeyRunParameters}
     * @return   parameter "cmonkey_run_result_id" of String
     */
    @JsonServerMethod(rpc = "Cmonkey.build_cmonkey_network_from_ws")
    public String buildCmonkeyNetworkFromWs(String wsId, String collectionId, CmonkeyRunParameters params, AuthToken authPart) throws Exception {
        String returnVal = null;
        //BEGIN build_cmonkey_network_from_ws
        returnVal = CmonkeyServerCaller.buildCmonkeyNetworkFromWs(wsId, collectionId, params, authPart);
        //END build_cmonkey_network_from_ws
        return returnVal;
    }

    /**
     * <p>Original spec-file function name: build_cmonkey_network_job_from_ws</p>
     * <pre>
     * Starts cMonkey server run for a series of expression data stored in workspace and returns job ID of the run
     * string ws_id - workspace id
     * string series_id - kbase id of expression data series for cMonkey run
     * CmonkeyRunParameters params - parameters of cMonkey run
     * string job_id - identifier of cMonkey job
     * </pre>
     * @param   wsId   instance of String
     * @param   seriesId   instance of String
     * @param   params   instance of type {@link us.kbase.cmonkey.CmonkeyRunParameters CmonkeyRunParameters}
     * @return   parameter "cmonkey_run_result_job_id" of String
     */
    @JsonServerMethod(rpc = "Cmonkey.build_cmonkey_network_job_from_ws")
    public String buildCmonkeyNetworkJobFromWs(String wsId, String seriesId, CmonkeyRunParameters params, AuthToken authPart) throws Exception {
        String returnVal = null;
        //BEGIN build_cmonkey_network_job_from_ws
        returnVal = CmonkeyServerCaller.buildCmonkeyNetworkJobFromWs(wsId, seriesId, params, authPart);
        //END build_cmonkey_network_job_from_ws
        return returnVal;
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            System.out.println("Usage: <program> <server_port>");
            return;
        }
        new CmonkeyServer().startupServer(Integer.parseInt(args[0]));
    }
}
