
package us.kbase.cmonkey;

import java.util.HashMap;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * <p>Original spec-file type: CmonkeyRunResult</p>
 * <pre>
 * Represents data from a single run of cMonkey
 * string id - identifier of cMonkey run
 * string start_time - start time of cMonkey run
 * string finish_time - end time of cMonkey run
 * int iterations_number - number of iterations
 * int last_iteration - last iteration
 * CmonkeyRunParameters parameters - run parameters
 * CmonkeyNetwork network;
 * </pre>
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "id",
    "start_time",
    "finish_time",
    "iterations_number",
    "last_iteration",
    "parameters",
    "network"
})
public class CmonkeyRunResult {

    @JsonProperty("id")
    private String id;
    @JsonProperty("start_time")
    private String startTime;
    @JsonProperty("finish_time")
    private String finishTime;
    @JsonProperty("iterations_number")
    private Long iterationsNumber;
    @JsonProperty("last_iteration")
    private Long lastIteration;
    /**
     * <p>Original spec-file type: CmonkeyRunParameters</p>
     * <pre>
     * Contains parameters of a cMonkey run
     * int networks_scoring = <0|1> - if 1, Network scoring will be used
     * int motifs_scoring = <0|1> - if 1, Motif scoring will be used
     * expression_series_ws_ref series_id - workspace id of expression data series;
     * genome_ws_ref genome_id - workspace id of genome;
     * operons_ws_ref operome_id - workspace id of operome;
     * network_ws_ref network_id - workspace id of network;
     * @optional genome_ref operome_ref network_ref
     * </pre>
     * 
     */
    @JsonProperty("parameters")
    private CmonkeyRunParameters parameters;
    /**
     * <p>Original spec-file type: CmonkeyNetwork</p>
     * <pre>
     * Represents network generated by a single run of cMonkey
     * string id - identifier of cMonkey-generated network
     * int iteration - number of the last iteration
     * string genome_name - organism name
     * int rows_number - number of rows
     * int columns_number - number of columns
     * int clusters_number - number of clusters
     * list<CmonkeyCluster> clusters - list of biclusters
     * @optional genome_name rows_number columns_number clusters_number clusters
     * </pre>
     * 
     */
    @JsonProperty("network")
    private CmonkeyNetwork network;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("id")
    public void setId(String id) {
        this.id = id;
    }

    public CmonkeyRunResult withId(String id) {
        this.id = id;
        return this;
    }

    @JsonProperty("start_time")
    public String getStartTime() {
        return startTime;
    }

    @JsonProperty("start_time")
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public CmonkeyRunResult withStartTime(String startTime) {
        this.startTime = startTime;
        return this;
    }

    @JsonProperty("finish_time")
    public String getFinishTime() {
        return finishTime;
    }

    @JsonProperty("finish_time")
    public void setFinishTime(String finishTime) {
        this.finishTime = finishTime;
    }

    public CmonkeyRunResult withFinishTime(String finishTime) {
        this.finishTime = finishTime;
        return this;
    }

    @JsonProperty("iterations_number")
    public Long getIterationsNumber() {
        return iterationsNumber;
    }

    @JsonProperty("iterations_number")
    public void setIterationsNumber(Long iterationsNumber) {
        this.iterationsNumber = iterationsNumber;
    }

    public CmonkeyRunResult withIterationsNumber(Long iterationsNumber) {
        this.iterationsNumber = iterationsNumber;
        return this;
    }

    @JsonProperty("last_iteration")
    public Long getLastIteration() {
        return lastIteration;
    }

    @JsonProperty("last_iteration")
    public void setLastIteration(Long lastIteration) {
        this.lastIteration = lastIteration;
    }

    public CmonkeyRunResult withLastIteration(Long lastIteration) {
        this.lastIteration = lastIteration;
        return this;
    }

    /**
     * <p>Original spec-file type: CmonkeyRunParameters</p>
     * <pre>
     * Contains parameters of a cMonkey run
     * int networks_scoring = <0|1> - if 1, Network scoring will be used
     * int motifs_scoring = <0|1> - if 1, Motif scoring will be used
     * expression_series_ws_ref series_id - workspace id of expression data series;
     * genome_ws_ref genome_id - workspace id of genome;
     * operons_ws_ref operome_id - workspace id of operome;
     * network_ws_ref network_id - workspace id of network;
     * @optional genome_ref operome_ref network_ref
     * </pre>
     * 
     */
    @JsonProperty("parameters")
    public CmonkeyRunParameters getParameters() {
        return parameters;
    }

    /**
     * <p>Original spec-file type: CmonkeyRunParameters</p>
     * <pre>
     * Contains parameters of a cMonkey run
     * int networks_scoring = <0|1> - if 1, Network scoring will be used
     * int motifs_scoring = <0|1> - if 1, Motif scoring will be used
     * expression_series_ws_ref series_id - workspace id of expression data series;
     * genome_ws_ref genome_id - workspace id of genome;
     * operons_ws_ref operome_id - workspace id of operome;
     * network_ws_ref network_id - workspace id of network;
     * @optional genome_ref operome_ref network_ref
     * </pre>
     * 
     */
    @JsonProperty("parameters")
    public void setParameters(CmonkeyRunParameters parameters) {
        this.parameters = parameters;
    }

    public CmonkeyRunResult withParameters(CmonkeyRunParameters parameters) {
        this.parameters = parameters;
        return this;
    }

    /**
     * <p>Original spec-file type: CmonkeyNetwork</p>
     * <pre>
     * Represents network generated by a single run of cMonkey
     * string id - identifier of cMonkey-generated network
     * int iteration - number of the last iteration
     * string genome_name - organism name
     * int rows_number - number of rows
     * int columns_number - number of columns
     * int clusters_number - number of clusters
     * list<CmonkeyCluster> clusters - list of biclusters
     * @optional genome_name rows_number columns_number clusters_number clusters
     * </pre>
     * 
     */
    @JsonProperty("network")
    public CmonkeyNetwork getNetwork() {
        return network;
    }

    /**
     * <p>Original spec-file type: CmonkeyNetwork</p>
     * <pre>
     * Represents network generated by a single run of cMonkey
     * string id - identifier of cMonkey-generated network
     * int iteration - number of the last iteration
     * string genome_name - organism name
     * int rows_number - number of rows
     * int columns_number - number of columns
     * int clusters_number - number of clusters
     * list<CmonkeyCluster> clusters - list of biclusters
     * @optional genome_name rows_number columns_number clusters_number clusters
     * </pre>
     * 
     */
    @JsonProperty("network")
    public void setNetwork(CmonkeyNetwork network) {
        this.network = network;
    }

    public CmonkeyRunResult withNetwork(CmonkeyNetwork network) {
        this.network = network;
        return this;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        return ((((((((((((((((("CmonkeyRunResult"+" [id=")+ id)+", startTime=")+ startTime)+", finishTime=")+ finishTime)+", iterationsNumber=")+ iterationsNumber)+", lastIteration=")+ lastIteration)+", parameters=")+ parameters)+", network=")+ network)+", additionalProperties=")+ additionalProperties)+"]");
    }

}
