package us.kbase.cmonkey;

import us.kbase.auth.AuthToken;
import us.kbase.common.service.JsonServerMethod;
import us.kbase.common.service.JsonServerServlet;

//BEGIN_HEADER
//END_HEADER

/**
 * <p>Original spec-file module name: Cmonkey</p>
 * <pre>
 * Module KBaseCmonkey version 1.0
 * This module provides a set of methods for work with cMonkey biclustering tool.
 * Data types summary
 * Input data types: 
 * ExpressionSeries from KBaseExpression service.
 * ExpressionSample from KBaseExpression service.
 * KBaseGenomes.Genome
 * Networks.InterationSet with operons data
 * Networks.InterationSet with STRING data
 * Output data types:
 * CmonkeyRun data type represents data generated by a single run of cMonkey (run_infos table of cMonkey results)
 * CmonkeyNetwork data type represents bicluster network
 * CmonkeyCluter data type represents a single bicluster from cMonkey network, with links to genes, experimental conditions and motifs
 * CmonkeyMotif data type represents a single motif identifed for a bicluster
 * Methods summary
 * build_cmonkey_network_job_from_ws - Starts cMonkey server run for a series of expression data stored in workspace and returns job ID of the run
 * </pre>
 */
public class CmonkeyServer extends JsonServerServlet {
    private static final long serialVersionUID = 1L;

    //BEGIN_CLASS_HEADER
    //END_CLASS_HEADER

    public CmonkeyServer() throws Exception {
        super("Cmonkey");
        //BEGIN_CONSTRUCTOR
        //END_CONSTRUCTOR
    }

    /**
     * <p>Original spec-file function name: run_cmonkey</p>
     * <pre>
     * Starts cMonkey server run for a series of expression data stored in workspace and returns job ID of the run
     * string ws_id - workspace id
     * CmonkeyRunParameters params - parameters of cMonkey run
     * string job_id - identifier of cMonkey job
     * </pre>
     * @param   wsId   instance of String
     * @param   params   instance of type {@link us.kbase.cmonkey.CmonkeyRunParameters CmonkeyRunParameters}
     * @return   parameter "cmonkey_run_result_job_id" of String
     */
    @JsonServerMethod(rpc = "Cmonkey.run_cmonkey")
    public String runCmonkey(String wsId, CmonkeyRunParameters params, AuthToken authPart) throws Exception {
        String returnVal = null;
        //BEGIN run_cmonkey
        returnVal = CmonkeyServerCaller.buildCmonkeyNetworkJobFromWs(wsId, params, authPart);
        //END run_cmonkey
        return returnVal;
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            System.out.println("Usage: <program> <server_port>");
            return;
        }
        new CmonkeyServer().startupServer(Integer.parseInt(args[0]));
    }
}
