
package us.kbase.cmonkey;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * <p>Original spec-file type: CmonkeyNetwork</p>
 * <pre>
 * Represents network generated by a single run of cMonkey
 * string id - identifier of cMonkey-generated network
 * int iteration - number of the last iteration
 * list<CmonkeyCluster> clusters - list of biclusters
 * </pre>
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "id",
    "iteration",
    "clusters"
})
public class CmonkeyNetwork {

    @JsonProperty("id")
    private String id;
    @JsonProperty("iteration")
    private Long iteration;
    @JsonProperty("clusters")
    private List<CmonkeyCluster> clusters;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("id")
    public void setId(String id) {
        this.id = id;
    }

    public CmonkeyNetwork withId(String id) {
        this.id = id;
        return this;
    }

    @JsonProperty("iteration")
    public Long getIteration() {
        return iteration;
    }

    @JsonProperty("iteration")
    public void setIteration(Long iteration) {
        this.iteration = iteration;
    }

    public CmonkeyNetwork withIteration(Long iteration) {
        this.iteration = iteration;
        return this;
    }

    @JsonProperty("clusters")
    public List<CmonkeyCluster> getClusters() {
        return clusters;
    }

    @JsonProperty("clusters")
    public void setClusters(List<CmonkeyCluster> clusters) {
        this.clusters = clusters;
    }

    public CmonkeyNetwork withClusters(List<CmonkeyCluster> clusters) {
        this.clusters = clusters;
        return this;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        return ((((((((("CmonkeyNetwork"+" [id=")+ id)+", iteration=")+ iteration)+", clusters=")+ clusters)+", additionalProperties=")+ additionalProperties)+"]");
    }

}
