package Bio::KBase::cmonkey::cmonkeyImpl;
use strict;
use Bio::KBase::Exceptions;
# Use Semantic Versioning (2.0.0-rc.1)
# http://semver.org 
our $VERSION = "0.1.0";

=head1 NAME

Cmonkey

=head1 DESCRIPTION

Module KBaseCmonkey version 1.0
This module provides a set of methods for work with cMonkey biclustering tool.

Data types summary
Input data types: 
ExpressionDataSeries represents a list of expression data samples that serve as an input of cMonkey.
ExpressionDataSample data type represents a sample of expression data for a single condition.
ExpressionDataPoint data type represents a relative expression value for a single gene.
Output data types:
CmonkeyRun data type represents data generated by a single run of cMonkey (run_infos table of cMonkey results)
CmonkeyNetwork data type represents bicluster network
CmonkeyCluter data type represents a single bicluster from cMonkey network, with links to genes, experimental conditions and motifs
CmonkeyMotif data type represents a single motif identifed for a bicluster

Methods summary
build_cmonkey_network - Starts cMonkey server run for a series of expression data and returns job ID of the run 
build_cmonkey_network_from_ws - Starts cMonkey server run for a series of expression data stored in workspace and returns job ID of the run
build_cmonkey_network_job_from_ws - Starts cMonkey server run for a series of expression data stored in workspace and returns job ID of the run

=cut

#BEGIN_HEADER
#END_HEADER

sub new
{
    my($class, @args) = @_;
    my $self = {
    };
    bless $self, $class;
    #BEGIN_CONSTRUCTOR
    #END_CONSTRUCTOR

    if ($self->can('_init_instance'))
    {
	$self->_init_instance();
    }
    return $self;
}

=head1 METHODS



=head2 build_cmonkey_network

  $cmonkey_run_result = $obj->build_cmonkey_network($series, $params)

=over 4

=item Parameter and return types

=begin html

<pre>
$series is a Cmonkey.ExpressionDataSeries
$params is a Cmonkey.CmonkeyRunParameters
$cmonkey_run_result is a Cmonkey.CmonkeyRunResult
ExpressionDataSeries is a reference to a hash where the following keys are defined:
	id has a value which is a string
	samples has a value which is a reference to a list where each element is a Cmonkey.ExpressionDataSample
ExpressionDataSample is a reference to a hash where the following keys are defined:
	id has a value which is a string
	description has a value which is a string
	points has a value which is a reference to a list where each element is a Cmonkey.ExpressionDataPoint
ExpressionDataPoint is a reference to a hash where the following keys are defined:
	gene_id has a value which is a string
	expression_value has a value which is a float
CmonkeyRunParameters is a reference to a hash where the following keys are defined:
	no_operons has a value which is an int
	no_string has a value which is an int
	no_networks has a value which is an int
	no_motifs has a value which is an int
CmonkeyRunResult is a reference to a hash where the following keys are defined:
	id has a value which is a string
	start_time has a value which is a string
	finish_time has a value which is a string
	iterations_number has a value which is an int
	last_iteration has a value which is an int
	organism has a value which is a string
	rows_number has a value which is an int
	columns_number has a value which is an int
	clusters_number has a value which is an int
	parameters has a value which is a Cmonkey.CmonkeyRunParameters
	network has a value which is a Cmonkey.CmonkeyNetwork
CmonkeyNetwork is a reference to a hash where the following keys are defined:
	id has a value which is a string
	iteration has a value which is an int
	clusters has a value which is a reference to a list where each element is a Cmonkey.CmonkeyCluster
CmonkeyCluster is a reference to a hash where the following keys are defined:
	id has a value which is a string
	residual has a value which is a float
	dataset_ids has a value which is a reference to a list where each element is a string
	gene_ids has a value which is a reference to a list where each element is a string
	motifs has a value which is a reference to a list where each element is a Cmonkey.CmonkeyMotif
CmonkeyMotif is a reference to a hash where the following keys are defined:
	id has a value which is a string
	seq_type has a value which is a string
	pssm_id has a value which is an int
	evalue has a value which is a float
	pssm_rows has a value which is a reference to a list where each element is a reference to a list where each element is a float
	hits has a value which is a reference to a list where each element is a Cmonkey.MastHit
	sites has a value which is a reference to a list where each element is a Cmonkey.SiteMeme
MastHit is a reference to a hash where the following keys are defined:
	sequence_id has a value which is a string
	strand has a value which is a string
	pssm_id has a value which is a string
	hit_start has a value which is an int
	hit_end has a value which is an int
	score has a value which is a float
	hit_pvalue has a value which is a float
SiteMeme is a reference to a hash where the following keys are defined:
	source_sequence_id has a value which is a string
	start has a value which is an int
	pvalue has a value which is a float
	left_flank has a value which is a string
	right_flank has a value which is a string
	sequence has a value which is a string

</pre>

=end html

=begin text

$series is a Cmonkey.ExpressionDataSeries
$params is a Cmonkey.CmonkeyRunParameters
$cmonkey_run_result is a Cmonkey.CmonkeyRunResult
ExpressionDataSeries is a reference to a hash where the following keys are defined:
	id has a value which is a string
	samples has a value which is a reference to a list where each element is a Cmonkey.ExpressionDataSample
ExpressionDataSample is a reference to a hash where the following keys are defined:
	id has a value which is a string
	description has a value which is a string
	points has a value which is a reference to a list where each element is a Cmonkey.ExpressionDataPoint
ExpressionDataPoint is a reference to a hash where the following keys are defined:
	gene_id has a value which is a string
	expression_value has a value which is a float
CmonkeyRunParameters is a reference to a hash where the following keys are defined:
	no_operons has a value which is an int
	no_string has a value which is an int
	no_networks has a value which is an int
	no_motifs has a value which is an int
CmonkeyRunResult is a reference to a hash where the following keys are defined:
	id has a value which is a string
	start_time has a value which is a string
	finish_time has a value which is a string
	iterations_number has a value which is an int
	last_iteration has a value which is an int
	organism has a value which is a string
	rows_number has a value which is an int
	columns_number has a value which is an int
	clusters_number has a value which is an int
	parameters has a value which is a Cmonkey.CmonkeyRunParameters
	network has a value which is a Cmonkey.CmonkeyNetwork
CmonkeyNetwork is a reference to a hash where the following keys are defined:
	id has a value which is a string
	iteration has a value which is an int
	clusters has a value which is a reference to a list where each element is a Cmonkey.CmonkeyCluster
CmonkeyCluster is a reference to a hash where the following keys are defined:
	id has a value which is a string
	residual has a value which is a float
	dataset_ids has a value which is a reference to a list where each element is a string
	gene_ids has a value which is a reference to a list where each element is a string
	motifs has a value which is a reference to a list where each element is a Cmonkey.CmonkeyMotif
CmonkeyMotif is a reference to a hash where the following keys are defined:
	id has a value which is a string
	seq_type has a value which is a string
	pssm_id has a value which is an int
	evalue has a value which is a float
	pssm_rows has a value which is a reference to a list where each element is a reference to a list where each element is a float
	hits has a value which is a reference to a list where each element is a Cmonkey.MastHit
	sites has a value which is a reference to a list where each element is a Cmonkey.SiteMeme
MastHit is a reference to a hash where the following keys are defined:
	sequence_id has a value which is a string
	strand has a value which is a string
	pssm_id has a value which is a string
	hit_start has a value which is an int
	hit_end has a value which is an int
	score has a value which is a float
	hit_pvalue has a value which is a float
SiteMeme is a reference to a hash where the following keys are defined:
	source_sequence_id has a value which is a string
	start has a value which is an int
	pvalue has a value which is a float
	left_flank has a value which is a string
	right_flank has a value which is a string
	sequence has a value which is a string


=end text



=item Description

Starts cMonkey server run for a series of expression data and returns run result 
ExpressionDataSeries series - series of expression data samples for cMonkey run
CmonkeyRunParameters params - parameters of cMonkey run
string job_id - identifier of cMonkey job

=back

=cut

sub build_cmonkey_network
{
    my $self = shift;
    my($series, $params) = @_;

    my @_bad_arguments;
    (ref($series) eq 'HASH') or push(@_bad_arguments, "Invalid type for argument \"series\" (value was \"$series\")");
    (ref($params) eq 'HASH') or push(@_bad_arguments, "Invalid type for argument \"params\" (value was \"$params\")");
    if (@_bad_arguments) {
	my $msg = "Invalid arguments passed to build_cmonkey_network:\n" . join("", map { "\t$_\n" } @_bad_arguments);
	Bio::KBase::Exceptions::ArgumentValidationError->throw(error => $msg,
							       method_name => 'build_cmonkey_network');
    }

    my $ctx = $Bio::KBase::cmonkey::Service::CallContext;
    my($cmonkey_run_result);
    #BEGIN build_cmonkey_network
    #END build_cmonkey_network
    my @_bad_returns;
    (ref($cmonkey_run_result) eq 'HASH') or push(@_bad_returns, "Invalid type for return variable \"cmonkey_run_result\" (value was \"$cmonkey_run_result\")");
    if (@_bad_returns) {
	my $msg = "Invalid returns passed to build_cmonkey_network:\n" . join("", map { "\t$_\n" } @_bad_returns);
	Bio::KBase::Exceptions::ArgumentValidationError->throw(error => $msg,
							       method_name => 'build_cmonkey_network');
    }
    return($cmonkey_run_result);
}




=head2 build_cmonkey_network_from_ws

  $cmonkey_run_result_id = $obj->build_cmonkey_network_from_ws($ws_id, $collection_id, $params)

=over 4

=item Parameter and return types

=begin html

<pre>
$ws_id is a string
$collection_id is a string
$params is a Cmonkey.CmonkeyRunParameters
$cmonkey_run_result_id is a string
CmonkeyRunParameters is a reference to a hash where the following keys are defined:
	no_operons has a value which is an int
	no_string has a value which is an int
	no_networks has a value which is an int
	no_motifs has a value which is an int

</pre>

=end html

=begin text

$ws_id is a string
$collection_id is a string
$params is a Cmonkey.CmonkeyRunParameters
$cmonkey_run_result_id is a string
CmonkeyRunParameters is a reference to a hash where the following keys are defined:
	no_operons has a value which is an int
	no_string has a value which is an int
	no_networks has a value which is an int
	no_motifs has a value which is an int


=end text



=item Description

Starts cMonkey server run for a series of expression data stored in workspace and returns ID of the run result object
string ws_id - workspace id
string series_id - kbase id of expression data series for cMonkey run
CmonkeyRunParameters params - parameters of cMonkey run
string job_id - identifier of cMonkey job

=back

=cut

sub build_cmonkey_network_from_ws
{
    my $self = shift;
    my($ws_id, $collection_id, $params) = @_;

    my @_bad_arguments;
    (!ref($ws_id)) or push(@_bad_arguments, "Invalid type for argument \"ws_id\" (value was \"$ws_id\")");
    (!ref($collection_id)) or push(@_bad_arguments, "Invalid type for argument \"collection_id\" (value was \"$collection_id\")");
    (ref($params) eq 'HASH') or push(@_bad_arguments, "Invalid type for argument \"params\" (value was \"$params\")");
    if (@_bad_arguments) {
	my $msg = "Invalid arguments passed to build_cmonkey_network_from_ws:\n" . join("", map { "\t$_\n" } @_bad_arguments);
	Bio::KBase::Exceptions::ArgumentValidationError->throw(error => $msg,
							       method_name => 'build_cmonkey_network_from_ws');
    }

    my $ctx = $Bio::KBase::cmonkey::Service::CallContext;
    my($cmonkey_run_result_id);
    #BEGIN build_cmonkey_network_from_ws
    #END build_cmonkey_network_from_ws
    my @_bad_returns;
    (!ref($cmonkey_run_result_id)) or push(@_bad_returns, "Invalid type for return variable \"cmonkey_run_result_id\" (value was \"$cmonkey_run_result_id\")");
    if (@_bad_returns) {
	my $msg = "Invalid returns passed to build_cmonkey_network_from_ws:\n" . join("", map { "\t$_\n" } @_bad_returns);
	Bio::KBase::Exceptions::ArgumentValidationError->throw(error => $msg,
							       method_name => 'build_cmonkey_network_from_ws');
    }
    return($cmonkey_run_result_id);
}




=head2 build_cmonkey_network_job_from_ws

  $cmonkey_run_result_job_id = $obj->build_cmonkey_network_job_from_ws($ws_id, $series_id, $params)

=over 4

=item Parameter and return types

=begin html

<pre>
$ws_id is a string
$series_id is a string
$params is a Cmonkey.CmonkeyRunParameters
$cmonkey_run_result_job_id is a string
CmonkeyRunParameters is a reference to a hash where the following keys are defined:
	no_operons has a value which is an int
	no_string has a value which is an int
	no_networks has a value which is an int
	no_motifs has a value which is an int

</pre>

=end html

=begin text

$ws_id is a string
$series_id is a string
$params is a Cmonkey.CmonkeyRunParameters
$cmonkey_run_result_job_id is a string
CmonkeyRunParameters is a reference to a hash where the following keys are defined:
	no_operons has a value which is an int
	no_string has a value which is an int
	no_networks has a value which is an int
	no_motifs has a value which is an int


=end text



=item Description

Starts cMonkey server run for a series of expression data stored in workspace and returns job ID of the run
string ws_id - workspace id
string series_id - kbase id of expression data series for cMonkey run
CmonkeyRunParameters params - parameters of cMonkey run
string job_id - identifier of cMonkey job

=back

=cut

sub build_cmonkey_network_job_from_ws
{
    my $self = shift;
    my($ws_id, $series_id, $params) = @_;

    my @_bad_arguments;
    (!ref($ws_id)) or push(@_bad_arguments, "Invalid type for argument \"ws_id\" (value was \"$ws_id\")");
    (!ref($series_id)) or push(@_bad_arguments, "Invalid type for argument \"series_id\" (value was \"$series_id\")");
    (ref($params) eq 'HASH') or push(@_bad_arguments, "Invalid type for argument \"params\" (value was \"$params\")");
    if (@_bad_arguments) {
	my $msg = "Invalid arguments passed to build_cmonkey_network_job_from_ws:\n" . join("", map { "\t$_\n" } @_bad_arguments);
	Bio::KBase::Exceptions::ArgumentValidationError->throw(error => $msg,
							       method_name => 'build_cmonkey_network_job_from_ws');
    }

    my $ctx = $Bio::KBase::cmonkey::Service::CallContext;
    my($cmonkey_run_result_job_id);
    #BEGIN build_cmonkey_network_job_from_ws
    #END build_cmonkey_network_job_from_ws
    my @_bad_returns;
    (!ref($cmonkey_run_result_job_id)) or push(@_bad_returns, "Invalid type for return variable \"cmonkey_run_result_job_id\" (value was \"$cmonkey_run_result_job_id\")");
    if (@_bad_returns) {
	my $msg = "Invalid returns passed to build_cmonkey_network_job_from_ws:\n" . join("", map { "\t$_\n" } @_bad_returns);
	Bio::KBase::Exceptions::ArgumentValidationError->throw(error => $msg,
							       method_name => 'build_cmonkey_network_job_from_ws');
    }
    return($cmonkey_run_result_job_id);
}




=head2 version 

  $return = $obj->version()

=over 4

=item Parameter and return types

=begin html

<pre>
$return is a string
</pre>

=end html

=begin text

$return is a string

=end text

=item Description

Return the module version. This is a Semantic Versioning number.

=back

=cut

sub version {
    return $VERSION;
}

=head1 TYPES



=head2 ExpressionDataPoint

=over 4



=item Description

Represents a particular data point from gene expression data set
string gene_id - KBase gene identifier
float expression_value - relative expression value


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
gene_id has a value which is a string
expression_value has a value which is a float

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
gene_id has a value which is a string
expression_value has a value which is a float


=end text

=back



=head2 ExpressionDataSample

=over 4



=item Description

ExpressionDataSample represents set of expression data
string id - identifier of data set
string description - description of data set`
list<ExpressionDataPoint> points - data points


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
id has a value which is a string
description has a value which is a string
points has a value which is a reference to a list where each element is a Cmonkey.ExpressionDataPoint

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
id has a value which is a string
description has a value which is a string
points has a value which is a reference to a list where each element is a Cmonkey.ExpressionDataPoint


=end text

=back



=head2 ExpressionDataSeries

=over 4



=item Description

ExpressionDataSeries represents collection of expression data samples
string id - identifier of the collection
list<ExpressionDataSample> samples - data sets


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
id has a value which is a string
samples has a value which is a reference to a list where each element is a Cmonkey.ExpressionDataSample

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
id has a value which is a string
samples has a value which is a reference to a list where each element is a Cmonkey.ExpressionDataSample


=end text

=back



=head2 MastHit

=over 4



=item Description

Represents a particular MAST hit
string sequence_id - name of sequence
string strand - strand ("+" or "-")
string pssm_id - name of motif
int hit_start - start position of hit
int hit_end - end position of hit
float score - hit score
float hit_pvalue - hit p-value


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
sequence_id has a value which is a string
strand has a value which is a string
pssm_id has a value which is a string
hit_start has a value which is an int
hit_end has a value which is an int
score has a value which is a float
hit_pvalue has a value which is a float

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
sequence_id has a value which is a string
strand has a value which is a string
pssm_id has a value which is a string
hit_start has a value which is an int
hit_end has a value which is an int
score has a value which is a float
hit_pvalue has a value which is a float


=end text

=back



=head2 PssmRow

=over 4



=item Description

Represents a single row of PSSM
int rowNumber - number of PSSM row
float aWeight 
float cWeight
float gWeight
float tWeight


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
row_number has a value which is an int
a_weight has a value which is a float
c_weight has a value which is a float
g_weight has a value which is a float
t_weight has a value which is a float

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
row_number has a value which is an int
a_weight has a value which is a float
c_weight has a value which is a float
g_weight has a value which is a float
t_weight has a value which is a float


=end text

=back



=head2 SiteMeme

=over 4



=item Description

Represents a particular site from MEME motif description 
string source_sequence_id - ID of sequence where the site was found
int start - position of site start 
float pvalue - site P-value
string left_flank - sequence of left flank
string sequence - sequence of site
string right_flank - sequence of right flank


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
source_sequence_id has a value which is a string
start has a value which is an int
pvalue has a value which is a float
left_flank has a value which is a string
right_flank has a value which is a string
sequence has a value which is a string

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
source_sequence_id has a value which is a string
start has a value which is an int
pvalue has a value which is a float
left_flank has a value which is a string
right_flank has a value which is a string
sequence has a value which is a string


=end text

=back



=head2 CmonkeyMotif

=over 4



=item Description

Represents motif generated by cMonkey with a list of hits in upstream sequences
string CmonkeyMotifId - identifier of MotifCmonkey
string seqType - type of sequence
int pssm_id - number of motif
float evalue - motif e-value
list<PssmRow> pssm - PSSM 
list<HitMast> hits - hits (motif annotations)
list<SiteMeme> sites - training set


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
id has a value which is a string
seq_type has a value which is a string
pssm_id has a value which is an int
evalue has a value which is a float
pssm_rows has a value which is a reference to a list where each element is a reference to a list where each element is a float
hits has a value which is a reference to a list where each element is a Cmonkey.MastHit
sites has a value which is a reference to a list where each element is a Cmonkey.SiteMeme

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
id has a value which is a string
seq_type has a value which is a string
pssm_id has a value which is an int
evalue has a value which is a float
pssm_rows has a value which is a reference to a list where each element is a reference to a list where each element is a float
hits has a value which is a reference to a list where each element is a Cmonkey.MastHit
sites has a value which is a reference to a list where each element is a Cmonkey.SiteMeme


=end text

=back



=head2 CmonkeyCluster

=over 4



=item Description

Represents bicluster generated by cMonkey
string id - identifier of bicluster
float residual - residual
list<string> dataset_ids - list of experimental conditions 
list<string> gene_ids - list of genes from bicluster
list<CmonkeyMotif> motifs - list of motifs identified for the bicluster, converted to MEME format


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
id has a value which is a string
residual has a value which is a float
dataset_ids has a value which is a reference to a list where each element is a string
gene_ids has a value which is a reference to a list where each element is a string
motifs has a value which is a reference to a list where each element is a Cmonkey.CmonkeyMotif

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
id has a value which is a string
residual has a value which is a float
dataset_ids has a value which is a reference to a list where each element is a string
gene_ids has a value which is a reference to a list where each element is a string
motifs has a value which is a reference to a list where each element is a Cmonkey.CmonkeyMotif


=end text

=back



=head2 CmonkeyNetwork

=over 4



=item Description

Represents network generated by a single run of cMonkey
string id - identifier of cMonkey-generated network
int iteration - number of the last iteration
list<CmonkeyCluster> clusters - list of biclusters


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
id has a value which is a string
iteration has a value which is an int
clusters has a value which is a reference to a list where each element is a Cmonkey.CmonkeyCluster

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
id has a value which is a string
iteration has a value which is an int
clusters has a value which is a reference to a list where each element is a Cmonkey.CmonkeyCluster


=end text

=back



=head2 CmonkeyRunParameters

=over 4



=item Description

Contains parameters of a cMonkey run
int no_operons = <0|1> - if 1, MicrobesOnline operons data will not be used
int no_string = <0|1> - if 1, STRING data will not be used
int no_networks = <0|1> - if 1, Network scoring will not be used
int no_motifs = <0|1> - if 1, Motif scoring will not be used


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
no_operons has a value which is an int
no_string has a value which is an int
no_networks has a value which is an int
no_motifs has a value which is an int

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
no_operons has a value which is an int
no_string has a value which is an int
no_networks has a value which is an int
no_motifs has a value which is an int


=end text

=back



=head2 CmonkeyRunResult

=over 4



=item Description

Represents data from a single run of cMonkey
string id - identifier of cMonkey run
string start_time - start time of cMonkey run
string finish_time - end time of cMonkey run
int iterations_number - number of iterations
int last_iteration - last iteration
string organism - organism
int rows_number - number of rows
int columns_number - number of columns
int clusters_number - number of clusters
CmonkeyRunParameters parameters - run parameters
CmonkeyNetwork network;


=item Definition

=begin html

<pre>
a reference to a hash where the following keys are defined:
id has a value which is a string
start_time has a value which is a string
finish_time has a value which is a string
iterations_number has a value which is an int
last_iteration has a value which is an int
organism has a value which is a string
rows_number has a value which is an int
columns_number has a value which is an int
clusters_number has a value which is an int
parameters has a value which is a Cmonkey.CmonkeyRunParameters
network has a value which is a Cmonkey.CmonkeyNetwork

</pre>

=end html

=begin text

a reference to a hash where the following keys are defined:
id has a value which is a string
start_time has a value which is a string
finish_time has a value which is a string
iterations_number has a value which is an int
last_iteration has a value which is an int
organism has a value which is a string
rows_number has a value which is an int
columns_number has a value which is an int
clusters_number has a value which is an int
parameters has a value which is a Cmonkey.CmonkeyRunParameters
network has a value which is a Cmonkey.CmonkeyNetwork


=end text

=back



=cut

1;
